backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets # Media files will be stored in the repo under images/uploads
collections:
  - name: "libros" # Used in routes, e.g., /admin/collections/blog
    label: "Libros" # Used in the UI
    folder: "libros" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
