site_url: https://disfrutandolalectura.com
display_url: https://disfrutandolalectura.com
media_folder: assets/uploads

backend:
  name: git-gateway
  branch: main

collections:
  - name: Settings
    label: Configuracion
    files:
      - label: Textos
        name: texts
        file: _data/text.yaml
        editor: false
        fields:
          - { label: "Texto", name: "body", widget: "text" }

  - name: lecturas # Used in routes, e.g., /admin/collections/blog
    label: Lecturas # Used in the UI
    folder: lecturas # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Layout, name: layout, widget: hidden, default: category }
      - { label: Lectura, name: taxonomy, widget: string, default: Aquitania }
      - {
          label: Link,
          name: permalink,
          widget: string,
          default: /lecturas/aquitania,
        }
      - { label: "Texto", name: "body", widget: "markdown" }

  - name: articulos # Used in routes, e.g., /admin/collections/blog
    label: Articulos # Used in the UI
    folder: libros/Aquitania/_posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}} # Filename template, e.g., YYYY-MM-DD-title.md"
    fields: # The fields for each document, usually in front matter
      - { label: Layout, name: layout, widget: hidden, default: single }
      - {
          label: Titulo,
          name: title,
          widget: string,
          default: Orden de análisis,
        }
      - { label: Fecha, name: date, widget: datetime }
      - { label: "Texto", name: "body", widget: "markdown" }
